resolver: lts-5.1

packages:
- 'clash-lib'
- 'clash-verilog'
- 'clash-systemverilog'
- 'clash-vhdl'
- 'clash-ghc'
- 'testsuite'
- location:
    git: https://github.com/clash-lang/clash-prelude.git
    commit: 39d5bbdab8c041e730a5ecb585608f83f8c803ad

extra-deps:
- ghc-typelits-natnormalise-0.4.1
